### PR TITLE
Fix setting the status URL for bitbucket

### LINKED ISSUE #588: Invalid URL passed to `url` field of bitbucket server build status
https://github.com/danger/danger-js/blob/d3287edf9c1d39334ed9986a244443d2432e9ccc/source/runner/Executor.ts#L248-L262

I'm a bit confused as to why the issue/pr url is being passed to the comment rather than the CI run URL? On BBS the `issueURL` isn't a full URL and causes this error:

```
Feedback: rest/api/1.0/projects/PROJ/repos/repo/pull-requests/106/diff#comment-27188
Request failed [400]: https://bitbucket.company/rest/build-status/1.0/commits/75bb67856c6cfdeed8682e279ccff899b1a77baa
Response: {
  "errors": [
    {
      "context": null,
      "message": "Please specify a valid url",
      "exceptionName": null
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by orta**
Fixes #588

### CODE REVIEW

File: source/platforms/BitBucketServer.ts [hunk 1]
```diff
@@ -232,8 +232,9 @@ export class BitBucketServer implements Platform {
     // https://bitbucket.org/atlassian/jiraconnect-ios/pull-requests/4/crash-groups/diff#comment-426
     // So take the PR and attack the comment, I think :D
 
+    const host = this.api.repoCredentials.host
     const prURL = this.api.getPRBasePath()
-    return issue && issue.id && `${prURL}/diff#comment-${issue.id}`
+    return issue && issue.id && `${host}${prURL}/diff#comment-${issue.id}`
```
Comment (azz) [inline source/platforms/BitBucketServer.ts]: The `prURL` here is the API URL (`rest/api/1.0/...`) which will link to the JSON blob of the diff, rather than the web UI.

Comment (orta) [reply source/platforms/BitBucketServer.ts]: Aww, well, at least it's not crashing - I had no way to test 💯
