### PR TITLE
[inline mode] fix empty comment

### LINKED ISSUE #563: Danger writes empty comment if it have inline comment but no main commet.
Danger writes an empty comment when it has one or more inline comments but no Main comment.

To reproduce you can use below danger file.
```
declare function warn(message: string, file?: string, line?: number): void

warn("Testing", "source/danger.d.ts", 174)
```

### PR DESCRIPTION
**Pull request by codestergit**
Fixes #563

### CODE REVIEW

File: source/dsl/DangerResults.ts [hunk 1]
```diff
@@ -208,6 +208,10 @@ export function sortResults(results: DangerResults): DangerResults {
   }
 }
 
+export function isEmpty(results: DangerResults): boolean {
```
Comment (orta) [inline source/dsl/DangerResults.ts]: Any chance this could mention results? `isEmptyResults`? Then this is good to go!

**Comment by orta** [comment]
Nice one!

**Comment by orta** [comment]
Congrats

**Comment by codestergit** [comment]
Adding these changes to #560.
