### PR TITLE
fix(Dangerfile): report errors when evaluating Dangerfile

### LINKED ISSUE #250: Danger eats exceptions
Adding `throw new Error('failure');` at the top of the `dangerfile.js` means that Danger will output nothing, with an exit code of `0` when running in local/PR mode. Instead, it should report the exception to the console, and set an exit code.

### PR DESCRIPTION
**Pull request by macklinu**
resolves #250 

This wraps our dangerfile evaluation in a try/catch (as suggested in [vm2's docs](https://github.com/patriksimek/vm2#error-handling)). I opted to report a failure to evaluate the dangerfile as a failure, so Danger will post the error's stack in the Danger results table. Thoughts on this?

Running `danger pr` locally:

```
ts-node source/commands/danger-pr.ts https://github.com/danger/danger-js/pull/336
Unable to evaluate the Dangerfile
{
  fails: [
    {
      message: "```
Error: failure
    at Object.<anonymous> (/Users/macklinu/dev/danger/danger-js/dangerfile.ts:6:7)
    at NodeVM.run (/Users/macklinu/dev/danger/danger-js/node_modules/vm2/lib/main.js:424:27)
    at Object.<anonymous> (/Users/macklinu/dev/danger/danger-js/source/runner/DangerfileRunner.ts:123:24)
    at step (/Users/macklinu/dev/danger/danger-js/source/runner/DangerfileRunner.ts:40:23)
    at Object.next (/Users/macklinu/dev/danger/danger-js/source/runner/DangerfileRunner.ts:21:53)
    at /Users/macklinu/dev/danger/danger-js/source/runner/DangerfileRunner.ts:15:71
    at __awaiter (/Users/macklinu/dev/danger/danger-js/source/runner/DangerfileRunner.ts:11:12)
    at Object.runDangerfileEnvironment (/Users/macklinu/dev/danger/danger-js/source/runner/DangerfileRunner.ts:111:12)
    at /Users/macklinu/dev/danger/danger-js/source/commands/danger-pr.ts:108:61
    at step (/Users/macklinu/dev/danger/danger-js/source/commands/danger-pr.ts:32:23)
```"
    }
  ],
  warnings: [],
  messages: [],
  markdowns: []
}
```

Lemme know what you think about this solution, I think this addresses the issue mentioned in #250.

### CODE REVIEW

File: source/runner/DangerfileRunner.ts [hunk 1]
```diff
@@ -92,26 +92,36 @@ export async function runDangerfileEnvironment(
...
+    return {
+      fails: results.fails,
+      warnings: results.warnings,
+      messages: results.messages,
+      markdowns: results.markdowns,
+    }
+  } catch (e) {
+    console.error("Unable to evaluate the Dangerfile")
+    return {
+      fails: [{ message: `\`\`\`\n${e.stack}\n\`\`\`` }],
```
Comment (macklinu) [inline source/runner/DangerfileRunner.ts]: This is a little funky syntax-wise, but I can clean this up if we want to report the error stack in the Danger results table on GitHub. 👍

**Comment by orta** [comment]
Yeah, I iterated on this a bit in Peril, so maybe just steal that code out-right: https://github.com/danger/peril/blob/master/source/danger/danger_runner.ts#L68

Then it can happen in Danger instead. Which is nice because we may be able to still show any results that have also already been stored pre-exception.

**Comment by orta** [comment]
Including the line in the Dangerfile (maybe instead of the whole one) would be awesome, could look through the stack to find the file line in the danger file, then highlight using something like the diff syntax highlighter:

```diff
const packageText = fs.readFileSync("package.json", "utf8")
if (packageText.includes("yarn run")) {
  const url = "https://github.com/yarnpkg/yarn/issues/3595"
-  fail(`You have a \`yarn run\` inside the package.json. This is probably a mistake, see ${url}.`)
}
```

File: source/runner/DangerfileRunner.ts [hunk 2]
```diff
@@ -92,29 +92,50 @@ export async function runDangerfileEnvironment(
...
+/** Returns Markdown results to post if an exception is raised during the danger run */
+const resultsForCaughtError = (file: string, contents: string, error: Error): DangerResults => {
+  const failure = `Danger failed to run \`${file}\`.`
+  const errorMD = `## Error ${error.name}
+\`\`\`
+${error.message}
+${error.stack}
+\`\`\`
+### Dangerfile
+\`\`\`
```
Comment (macklinu) [inline source/runner/DangerfileRunner.ts]: I removed the ts for now - will look into showing which line caused the problem next. 👍

**Comment by macklinu** [comment]
Playing around with [pinpoint](https://www.npmjs.com/package/pinpoint) in 7c29d40 - thoughts? (thanks for pointing this out a while ago, @tivac - looked through the Danger slack to find out which module this was. 👍 )

```
ts-node source/commands/danger-pr.ts https://github.com/danger/danger-js/pull/336
Unable to evaluate the Dangerfile
{
  fails: [
    {
      message: "Danger failed to run `dangerfile.ts`."
    }
  ],
  warnings: [],
  markdowns: ["## Error Error
\`\`\`
haha
Error: haha
    at Error (native)
    at Object.<anonymous> (/Users/macklinu/dev/danger/danger-js/dangerfile.ts:6:7)
    at NodeVM.run (/Users/macklinu/dev/danger/danger-js/node_modules/vm2/lib/main.js:424:27)
    at Object.<anonymous> (/Users/macklinu/dev/danger/danger-js/source/runner/DangerfileRunner.ts:124:24)
    at step (/Users/macklinu/dev/danger/danger-js/source/runner/DangerfileRunner.ts:40:23)
    at Object.next (/Users/macklinu/dev/danger/danger-js/source/runner/DangerfileRunner.ts:21:53)
    at /Users/macklinu/dev/danger/danger-js/source/runner/DangerfileRunner.ts:15:71
    at __awaiter (/Users/macklinu/dev/danger/danger-js/source/runner/DangerfileRunner.ts:11:12)
    at Object.runDangerfileEnvironment (/Users/macklinu/dev/danger/danger-js/source/runner/DangerfileRunner.ts:112:12)
    at /Users/macklinu/dev/danger/danger-js/source/commands/danger-pr.ts:108:61
\`\`\`
### Dangerfile
\`\`\`
1| // Because we don't get to use the d.ts, we can pass in a subset here.
2| // This means we can re-use the type infra from the app, without having to
3| // fake the import.
4|
5| throw Error("haha")
--------^
6|
7| import { DangerDSL } from "./source/dsl/DangerDSL"
8| declare var danger: DangerDSL
9| declare var results: any
\`\`\`
  "],
  messages: []
}
```

**Comment by orta** [comment]
Interesting, that "NO LICENSE FOUND" is incorrect

**Comment by orta** [comment]
screen shot 2017-08-15 at 11 43 45

**Comment by orta** [comment]
Yeah, let's do this
