### PR TITLE
fix: GitLab Inline comments deleted with main comment updates

### LINKED ISSUE #1351: [BUG] Inline comments often don't show up, or show incorrectly with GitLab self-hosted
**Describe the bug**
I'm unable to get inline comments to show up correctly, and consistently, with danger-js and GitLab. While danger correctly adds a comment at the line I'd expect, the comment text is incorrect.

**To Reproduce**
1. Setup a new repo
2. Add the `.gitlab-ci.yml` file listed below
3. Add a test file, `LinterTest.swift` listed below
4. Add the example dangerfile
5. Push up to main
6. Branch off main
7. Edit the `LinterTest.swift`, removing the comments in lines 22-26
8. Push up the change and look at the pipeline for the merge request

<details>
  <summary>.gitlab-ci.yml</summary>

```yaml
stages:
  - analysis

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  FF_ENABLE_JOB_CLEANUP: 'true'

before_script:
  - eval "$(/opt/homebrew/bin/brew shellenv)"
  - brew install danger/tap/danger-js

.mr:
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE=~ /^WIP:/

danger_ci:
  stage: analysis
  extends: .mr
  tags:
    - macos03 # adjust to your setup
  script:
    - echo "Running Danger"
    - DEBUG=* danger ci
  interruptible: true
```
</details>

<details>
  <summary>LinterTest.swift</summary>

  ```swift
  import Foundation

  class LinterTest {
      var a = "ab"

      func annoyLinter() {
          // Triggers swiftformat spaceAroundOperators
          for i in 0 ... 10 {
              print(i)
          } // touch file to check linting

          // Triggers swiftlint empty_count
          _ = a.count == 0
      }

      enum State {
          case unknown
          case loading
          case finished
      }

      //enum NewState {
          //case unknown
          //case loading
          //case finished
      //}
  }
  ```
</details>

<details>
<summary>dangerfile.ts</summary>

```typescript
import { danger } from "danger";

warn("inline warning, line 16", "LinterTest.swift", 16);

warn("global warning")

warn("inline warning, line 22", "LinterTest.swift", 22);

warn("global warning 2, electric boogaloo")
```
</details>

**Expected behavior**
There should be one inline comment, underneath line 22 of `LinterTest.swift`, with the text `inline warning, line 22`. There should be 3 warnings on the main page of the merge request:
* `inline warning, line 16` - as this line isn't part of the changed file, it may not show up at all
* `global warning`
* `global warning 2, electric boogaloo`

**Screenshots**
Overview
Screenshot 2023-01-27 at 15 29 11

Changes tab
Screenshot 2023-01-27 at 15 27 28

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          |  11.2.1
| node             | N/A
| npm              | N/A
| Operating System | macOS 12.6.2
| GitLab self-hosted | 15.3
| gitlab-runner | 15.3.0

### PR DESCRIPTION
**Pull request by DavidBrunow**
Fixes #1351 and possibly #1380.

I verified this fix with an inline comment and a main Danger note with `DANGER_GITLAB_USE_THREADS` both set and unset. With it unset all behavior looked good to me. 

With that flag set, I am seeing an issue where the main Danger note was replacing the inline comment. Since that is not the intended behavior I tested the latest release with that flag set and also saw the same bad behavior there. Since that behavior is consistent I'd like to move forward with this pull request without trying to fix that behavior.

### CODE REVIEW

File: source/platforms/GitLab.ts [hunk 1]
```diff
@@ -99,28 +100,49 @@ class GitLab implements Platform {
...
-    // comment created by danger, resulting in a discussion/thread. Otherwise we are left with dangling comments
-    // that will most likely have no meaning out of context.
-    const discussions = await this.getDangerDiscussions(dangerID)
-    const firstDiscussion = discussions.shift()
-    const existingNote = firstDiscussion?.notes[0]
-    // Delete all notes from all other danger discussions (discussions cannot be deleted as a whole):
-    await this.deleteNotes(this.reduceNotesFromDiscussions(discussions)) //delete the rest
-
-    let newOrUpdatedNote: GitLabNote
+    if (useThreads()) {
```
Comment (DavidBrunow) [inline source/platforms/GitLab.ts:103]: The main difference in the approach in this pull request is to treat the new "create a thread for the main comment" behavior as completely separate from the previous behavior to "create a note for the main comment".

Mixing the logic of these two behaviors caused issues where certain scenarios were not handled, like trying to update the "main" Danger comment and instead updating an inline comment because it was a discussion and the "main" Danger comment was not.

File: source/platforms/GitLab.ts [hunk 2]
```diff
@@ -99,28 +100,49 @@ class GitLab implements Platform {
...
-    if (existingNote) {
-      // update the existing comment
-      newOrUpdatedNote = await this.api.updateMergeRequestNote(existingNote.id, newComment)
+      // create URL from note
+      // "https://gitlab.com/group/project/merge_requests/154#note_132143425"
+      return `${this.api.mergeRequestURL}#note_${newOrUpdatedNote.id}`
     } else {
-      // create a new comment
-      newOrUpdatedNote = await this.createComment(newComment)
+      const notes: GitLabNote[] = await this.getMainDangerNotes(dangerID)
```
Comment (DavidBrunow) [inline source/platforms/GitLab.ts:124]: This is copied from the code that existed before the change in https://github.com/danger/danger-js/pull/1331

File: source/platforms/GitLab.ts [hunk 3]
```diff
@@ -162,12 +184,24 @@ class GitLab implements Platform {
...
-    // comment by danger and thus created a discussion/thread. To not leave dangling notes, we delete the entire thread.
-    //There is no API to delete entire discussion. They can only be deleted fully by deleting every note:
-    const discussions = await this.getDangerDiscussions(dangerID)
-    return await this.deleteNotes(this.reduceNotesFromDiscussions(discussions))
+    if (useThreads()) {
+      //There is no API to delete entire discussion. They can only be deleted fully by deleting every note:
+      const discussions = await this.getDangerDiscussions(dangerID)
+      return await this.deleteNotes(this.reduceNotesFromDiscussions(discussions))
+    } else {
+      const notes = await this.getMainDangerNotes(dangerID)
```
Comment (DavidBrunow) [inline source/platforms/GitLab.ts:197]: This is copied from the code that existed before the change in https://github.com/danger/danger-js/pull/1331

**Comment by DavidBrunow** [comment]
@squarefrog No problem if you don't have the bandwidth, but if you do I'd appreciate you giving this branch a test.

**Comment by squarefrog** [comment]
I’m off work until next week but I can give it a try then, thanks for the tag!

**Comment by squarefrog** [comment]
I'm really sorry for the delay in testing this. I've been on leave from work, then we've had issues with our CI setup. I'll need to see if I can figure out how to build the binary of this branch then try it.

**Comment by squarefrog** [comment]
The good news is I figured out how to create a build of this and put it on our CI and it seems to work really well. Great job with this @DavidBrunow 🙌

**Comment by DavidBrunow** [comment]
@orta Do you want to review or do you recommend any other reviewers before merging this?

**Comment by LucasWeber-git** [comment]
We are facing the same problem here. @orta it would be great if you could approve this merge.

**Comment by orta** [comment]
Yeah, is @squarefrog  is happy, I am happy

**Comment by orta** [comment]
Shipped
